### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by thefirstLeonliao** [sipherxyz/comfyui-art-venture#55] opened 2024-10-31 08:52 UTC
cannot checkout to invalid path 'modules/controlnet/aux.py

**Comment by tungnguyensipher** [comment] 2024-10-31 13:19
Can you provide the log in console. I couldn't reproduce it on my end.

**Comment by tungnguyensipher** [comment] 2024-10-31 13:35
Should be fixed now

**Comment by bananasss00** [comment] 2024-10-31 13:40
> Should be fixed now

work now

**Closed** 2024-11-01 03:43 UTC

**Comment by thefirstLeonliao** [comment] 2024-11-01 07:54
work now，thank you
